// generated by scripts/adif_tables.ts
import { enums, Infer } from "superstruct";

export const antPath = [
  "G", // grayline
  "O", // other
  "S", // short path
  "L", // long path
] as const;

export const AntPathEnum = enums(antPath);
export type AntPathEnum = Infer<typeof AntPathEnum>;
