// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const antPath = [
  "G", // grayline
  "O", // other
  "S", // short path
  "L", // long path
] as const;

export const AntPathEnum = coerce(enums(antPath), string(), (value) => {
  const foundValue = antPath.find(
    (v) => v.toUpperCase() == value.toUpperCase()
  );

  return foundValue ?? value;
});

export type AntPathEnum = Infer<typeof AntPathEnum>;
