// generated by scripts/adif_tables.ts
import { enums, Infer } from "superstruct";

export const awardSponsor = [
  "ADIF_", // ADIF Development Group
  "ARI_", // ARI - l'Associazione Radioamatori Italiani
  "ARRL_", // ARRL - American Radio Relay League
  "CQ_", // CQ Magazine
  "DARC_", // DARC - Deutscher Amateur-Radio-Club e.V.
  "EQSL_", // eQSL
  "IARU_", // IARU - International Amateur Radio Union
  "JARL_", // JARL - Japan Amateur Radio League
  "RSGB_", // RSGB - Radio Society of Great Britain
  "TAG_", // TAG - Tambov award group
  "WABAG_", // WAB - Worked all Britain
] as const;

export const AwardSponsorEnum = enums(awardSponsor);
export type AwardSponsorEnum = Infer<typeof AwardSponsorEnum>;
