// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const continent = [
  "NA", // North America
  "SA", // South America
  "EU", // Europe
  "AF", // Africa
  "OC", // Oceana
  "AS", // Asia
  "AN", // Antarctica
] as const;

export const ContinentEnum = coerce(enums(continent), string(), (value) => {
  const foundValue = continent.find(
    (v) => v.toUpperCase() == value.toUpperCase()
  );

  return foundValue ?? value;
});

export type ContinentEnum = Infer<typeof ContinentEnum>;
