// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const eqslAg = [
  "Y", // The QSO's callsign holds eQSL.cc's "Authenticity Guaranteed" status
  "N", // The QSO's callsign does not hold eQSL.cc's "Authenticity Guaranteed" status
  "U", // Unspecified (Default)
] as const;

export const EqslAgEnum = coerce(enums(eqslAg), string(), (value) => {
  const foundValue = eqslAg.find((v) => v.toUpperCase() == value.toUpperCase());

  return foundValue ?? value;
});

export type EqslAgEnum = Infer<typeof EqslAgEnum>;
