// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const morseKeyType = [
  "SK", // Straight Key
  "SS", // Sideswiper
  "BUG", // Mechanical semi-automatic keyer or Bug
  "FAB", // Mechanical fully-automatic keyer or Bug
  "SP", // Single Paddle
  "DP", // Dual Paddle
  "CPU", // Computer Driven
] as const;

export const MorseKeyTypeEnum = coerce(
  enums(morseKeyType),
  string(),
  (value) => {
    const foundValue = morseKeyType.find(
      (v) => v.toUpperCase() == value.toUpperCase(),
    );

    return foundValue ?? value;
  },
);

export type MorseKeyTypeEnum = Infer<typeof MorseKeyTypeEnum>;
