// generated by scripts/adif_tables.ts
import { enums, Infer } from "superstruct";

export const primaryAdministrativeSubdivision = [
  "10", // Virovitičko-Podravska županija
  "11", // Požeško-Slavonska županija
  "12", // Brodsko-Posavska županija
  "13", // Zadarska županija
  "14", // Osječko-Baranjska županija
  "15", // Šibensko-Kninska županija
  "16", // Vukovarsko-Srijemska županija
  "17", // Splitsko-Dalmatinska županija
  "18", // Istarska županija
  "19", // Dubrovačko-Neretvanska županija
  "20", // Međimurska županija
  "21", // Grad Zagreb
  "22", // Kyoto
  "23", // Shiga
  "24", // Nara
  "25", // Osaka
  "26", // Wakayama
  "27", // Hyogo
  "28", // Toyama
  "29", // Fukui
  "30", // Ishikawa
  "31", // Okayama
  "32", // Shimane
  "33", // Yamaguchi
  "34", // Tottori
  "35", // Hiroshima
  "36", // Kagawa
  "37", // Tokushima
  "38", // Ehime
  "39", // Kochi
  "40", // Fukuoka
  "41", // Saga
  "42", // Nagasaki
  "43", // Kumamoto
  "44", // Oita
  "45", // Miyazaki
  "46", // Kagoshima
  "47", // Okinawa
  "48", // Lozère
  "49", // Maine-et-Loire
  "50", // Manche
  "51", // Marne
  "52", // Haute-Marne
  "53", // Mayenne
  "54", // Meurthe-et-Moselle
  "55", // Meuse
  "56", // Morbihan
  "57", // Moselle
  "58", // Niëvre
  "59", // Nord
  "60", // Oise
  "61", // Orne
  "62", // Pas-de-Calais
  "63", // Puy-de-Dôme
  "64", // Pyrénées-Atlantiques
  "65", // Hautea-Pyrénées
  "66", // Pyrénées-Orientales
  "67", // Bas-Rhin
  "68", // Haut-Rhin
  "69", // Rhône
  "70", // Haute-Saône
  "71", // Saône-et-Loire
  "72", // Sarthe
  "73", // Savoie
  "74", // Haute-Savoie
  "75", // Paris
  "76", // Seine-Maritime
  "77", // Seine-et-Marne
  "78", // Yvelines
  "79", // Deux-Sèvres
  "80", // Somme
  "81", // Tarn
  "82", // Tarn-et-Garonne
  "83", // Var
  "84", // Vaucluse
  "85", // Vendée
  "86", // Vienne
  "87", // Haute-Vienne
  "88", // Vosges
  "89", // Yonne
  "90", // Territoire de Belfort
  "91", // Essonne
  "92", // Hauts-de-Selne
  "93", // Seine-Saint-Denis
  "94", // Val-de-Marne
  "95", // Val-d'Oise
  "100", // Somero
  "101", // Copenhagen City
  "102", // Alastaro
  "103", // Askainen
  "104", // Aura
  "105", // Dragsfjärd
  "106", // Eura
  "107", // Eurajoki
  "108", // Halikko
  "109", // Harjavalta
  "110", // Honkajoki
  "111", // Houtskari
  "112", // Huittinen
  "115", // Iniö
  "116", // Jämijärvi
  "117", // Kaarina
  "119", // Kankaanpää
  "120", // Karinainen
  "122", // Karvia
  "123", // Äetsä
  "124", // Kemiö
  "126", // Kiikala
  "128", // Kiikoinen
  "129", // Kisko
  "130", // Kiukainen
  "131", // Kodisjoki
  "132", // Kokemäki
  "133", // Korppoo
  "134", // Koski tl
  "135", // Kullaa
  "136", // Kustavi
  "137", // Kuusjoki
  "138", // Köyliö
  "139", // Laitila
  "140", // Lappi
  "141", // Lavia
  "142", // Lemu
  "143", // Lieto
  "144", // Loimaa
  "145", // Loimaan kunta
  "147", // Luvia
  "148", // Marttila
  "149", // Masku
  "150", // Mellilä
  "151", // Merikarvia
  "152", // Merimasku
  "154", // Mietoinen
  "156", // Muurla
  "157", // Mynämäki
  "158", // Naantali
  "159", // Nakkila
  "160", // Nauvo
  "161", // Noormarkku
  "162", // Nousiainen
  "163", // Oripää
  "164", // Paimio
  "165", // Parainen
  "167", // Perniö
  "168", // Pertteli
  "169", // Piikkiö
  "170", // Pomarkku
  "171", // Pori
  "172", // Punkalaidun
  "173", // Pyhäranta
  "174", // Pöytyä
  "175", // Raisio
  "176", // Rauma
  "178", // Rusko
  "179", // Rymättylä
  "180", // Salo
  "181", // Sauvo
  "182", // Siikainen
  "183", // Suodenniemi
  "184", // Suomusjärvi
  "185", // Säkylä
  "186", // Särkisalo
  "187", // Taivassalo
  "188", // Tarvasjoki
  "189", // Turku
  "190", // Ulvila
  "191", // Uusikaupunki
  "192", // Vahto
  "193", // Vammala
  "194", // Vampula
  "195", // Vehmaa
  "196", // Velkua
  "198", // Västanfjärd
  "199", // Yläne
  "201", // Artjärvi
  "202", // Askola
  "204", // Espoo
  "205", // Hanko
  "206", // Helsinki
  "207", // Hyvinkää
  "208", // Inkoo
  "209", // Järvenpää
  "210", // Karjaa
  "211", // Karjalohja
  "212", // Karkkila
  "213", // Kauniainen
  "214", // Kerava
  "215", // Kirkkonummi
  "216", // Lapinjärvi
  "217", // Liljendal
  "218", // Lohjan kaupunki
  "220", // Loviisa
  "221", // Myrskylä
  "222", // Mäntsälä
  "223", // Nummi-Pusula
  "224", // Nurmijärvi
  "225", // Orimattila
  "226", // Pernaja
  "227", // Pohja
  "228", // Pornainen
  "229", // Porvoo
  "231", // Pukkila
  "233", // Ruotsinpyhtää
  "234", // Sammatti
  "235", // Sipoo
  "236", // Siuntio
  "238", // Tammisaari
  "241", // Tuusula
  "242", // Vantaa
  "243", // Vihti
  "301", // Asikkala
  "303", // Forssa
  "304", // Hattula
  "305", // Hauho
  "306", // Hausjärvi
  "307", // Hollola
  "308", // Humppila
  "309", // Hämeenlinna
  "310", // Janakkala
  "311", // Jokioinen
  "312", // Juupajoki
  "313", // Kalvola
  "314", // Kangasala
  "315", // Hämeenkoski
  "316", // Kuhmalahti
  "318", // Kuru
  "319", // Kylmäkoski
  "320", // Kärkölä
  "321", // Lahti
  "322", // Lammi
  "323", // Lempäälä
  "324", // Loppi
  "325", // Luopioinen
  "326", // Längelmäki
  "327", // Mänttä
  "328", // Nastola
  "329", // Nokia
  "330", // Orivesi
  "331", // Padasjoki
  "332", // Pirkkala
  "333", // Pälkäne
  "334", // Renko
  "335", // Riihimäki
  "336", // Ruovesi
  "337", // Sahalahti
  "340", // Tammela
  "341", // Tampere
  "342", // Toijala
  "344", // Tuulos
  "345", // Urjala
  "346", // Valkeakoski
  "347", // Vesilahti
  "348", // Viiala
  "349", // Vilppula
  "350", // Virrat
  "351", // Ylöjärvi
  "352", // Ypäjä
  "353", // Hämeenkyrö
  "354", // Ikaalinen
  "355", // Kihniö
  "356", // Mouhijärvi
  "357", // Parkano
  "358", // Viljakkala
  "402", // Enonkoski
  "403", // Hartola
  "404", // Haukivuori
  "405", // Heinola
  "407", // Heinävesi
  "408", // Hirvensalmi
  "409", // Joroinen
  "410", // Juva
  "411", // Jäppilä
  "412", // Kangaslampi
  "413", // Kangasniemi
  "414", // Kerimäki
  "415", // Mikkeli
  "417", // Mäntyharju
  "418", // Pertunmaa
  "419", // Pieksämäki
  "420", // Pieksänmaa
  "421", // Punkaharju
  "422", // Puumala
  "423", // Rantasalmi
  "424", // Ristiina
  "425", // Savonlinna
  "426", // Savonranta
  "427", // Sulkava
  "428", // Sysmä
  "502", // Elimäki
  "503", // Hamina
  "504", // Iitti
  "505", // Imatra
  "506", // Jaala
  "507", // Joutseno
  "509", // Kotka
  "510", // Kouvola
  "511", // Kuusankoski
  "513", // Lappeenranta
  "514", // Lemi
  "515", // Luumäki
  "516", // Miehikkälä
  "518", // Parikkala
  "519", // Pyhtää
  "520", // Rautjärvi
  "521", // Ruokolahti
  "522", // Saari
  "523", // Savitaipale
  "525", // Suomenniemi
  "526", // Taipalsaari
  "527", // Uukuniemi
  "528", // Valkeala
  "530", // Virolahti
  "531", // Ylämaa
  "532", // Anjalankoski
  "601", // Alahärmä
  "602", // Alajärvi
  "603", // Alavus
  "604", // Evijärvi
  "605", // Halsua
  "606", // Hankasalmi
  "607", // Himanka
  "608", // Ilmajoki
  "609", // Isojoki
  "610", // Isokyrö
  "611", // Jalasjärvi
  "612", // Joutsa
  "613", // Jurva
  "614", // Jyväskylä
  "615", // Jyväskylän mlk
  "616", // Jämsä
  "617", // Jämsänkoski
  "619", // Kannonkoski
  "620", // Kannus
  "621", // Karijoki
  "622", // Karstula
  "623", // Kaskinen
  "624", // Kauhajoki
  "625", // Kauhava
  "626", // Kaustinen
  "627", // Keuruu
  "628", // Kinnula
  "629", // Kivijärvi
  "630", // Kokkola
  "632", // Konnevesi
  "633", // Korpilahti
  "634", // Korsnäs
  "635", // Kortesjärvi
  "636", // Kristiinankaupunki
  "637", // Kruunupyy
  "638", // Kuhmoinen
  "639", // Kuortane
  "640", // Kurikka
  "641", // Kyyjärvi
  "642", // Kälviä
  "643", // Laihia
  "644", // Lappajärvi
  "645", // Lapua
  "646", // Laukaa
  "647", // Lehtimäki
  "648", // Leivonmäki
  "649", // Lestijärvi
  "650", // Lohtaja
  "651", // Luhanka
  "652", // Luoto
  "653", // Maalahti
  "654", // Maksamaa
  "655", // Multia
  "656", // Mustasaari
  "657", // Muurame
  "658", // Nurmo
  "659", // Närpiö
  "660", // Oravainen
  "661", // Perho
  "662", // Peräseinäjoki
  "663", // Petäjävesi
  "664", // Pietarsaari
  "665", // Pedersöre
  "666", // Pihtipudas
  "668", // Pylkönmäki
  "669", // Saarijärvi
  "670", // Seinäjoki
  "671", // Soini
  "672", // Sumiainen
  "673", // Suolahti
  "675", // Teuva
  "676", // Toholampi
  "677", // Toivakka
  "678", // Töysä
  "679", // Ullava
  "680", // Uurainen
  "681", // Uusikaarlepyy
  "682", // Vaasa
  "683", // Veteli
  "684", // Viitasaari
  "685", // Vimpeli
  "686", // Vähäkyrö
  "687", // Vöyri
  "688", // Ylihärmä
  "689", // Ylistaro
  "690", // Ähtäri
  "692", // Äänekoski
  "701", // Eno
  "702", // Iisalmi
  "703", // Ilomantsi
  "704", // Joensuu
  "705", // Juankoski
  "706", // Juuka
  "707", // Kaavi
  "708", // Karttula
  "709", // Keitele
  "710", // Kesälahti
  "711", // Kiihtelysvaara
  "712", // Kitee
  "713", // Kiuruvesi
  "714", // Kontiolahti
  "715", // Kuopio
  "716", // Lapinlahti
  "717", // Leppävirta
  "718", // Lieksa
  "719", // Liperi
  "720", // Maaninka
  "721", // Nilsiä
  "722", // Nurmes
  "723", // Outokumpu
  "724", // Pielavesi
  "725", // Polvijärvi
  "726", // Pyhäselkä
  "727", // Rautalampi
  "728", // Rautavaara
  "729", // Rääkkylä
  "730", // Siilinjärvi
  "731", // Sonkajärvi
  "732", // Suonenjoki
  "733", // Tervo
  "734", // Tohmajärvi
  "735", // Tuupovaara
  "736", // Tuusniemi
  "737", // Valtimo
  "738", // Varkaus
  "739", // Varpaisjärvi
  "740", // Vehmersalmi
  "741", // Vesanto
  "742", // Vieremä
  "743", // Värtsilä
  "801", // Alavieska
  "802", // Haapajärvi
  "803", // Haapavesi
  "804", // Hailuoto
  "805", // Haukipudas
  "806", // Hyrynsalmi
  "807", // Ii
  "808", // Kajaani
  "810", // Kalajoki
  "811", // Kempele
  "812", // Kestilä
  "813", // Kiiminki
  "814", // Kuhmo
  "815", // Kuivaniemi
  "816", // Kuusamo
  "817", // Kärsämäki
  "818", // Liminka
  "819", // Lumijoki
  "820", // Merijärvi
  "821", // Muhos
  "822", // Nivala
  "823", // Oulainen
  "824", // Oulu
  "825", // Oulunsalo
  "826", // Paltamo
  "827", // Pattijoki
  "828", // Piippola
  "829", // Pudasjärvi
  "830", // Pulkkila
  "831", // Puolanka
  "832", // Pyhäjoki
  "833", // Pyhäjärvi
  "834", // Pyhäntä
  "835", // Raahe
  "836", // Rantsila
  "837", // Reisjärvi
  "838", // Ristijärvi
  "839", // Ruukki
  "840", // Sievi
  "841", // Siikajoki
  "842", // Sotkamo
  "843", // Suomussalmi
  "844", // Taivalkoski
  "846", // Tyrnävä
  "847", // Utajärvi
  "848", // Vaala
  "849", // Vihanti
  "850", // Vuolijoki
  "851", // Yli-Ii
  "852", // Ylikiiminki
  "853", // Ylivieska
  "901", // Enontekiö
  "902", // Inari
  "903", // Kemi
  "904", // Keminmaa
  "905", // Kemijärvi
  "907", // Kittilä
  "908", // Kolari
  "909", // Muonio
  "910", // Pelkosenniemi
  "911", // Pello
  "912", // Posio
  "913", // Ranua
  "914", // Rovaniemi
  "915", // Rovaniemen mlk
  "916", // Salla
  "917", // Savukoski
  "918", // Simo
  "919", // Sodankylä
  "920", // Tervola
  "921", // Tornio
  "922", // Utsjoki
  "923", // Ylitornio
  "NS", // Novosibirsk
  "QC", // Québec
  "ON", // Ontario
  "MB", // Monza e Brianza
  "SK", // Saskatchewan
  "AB", // Stockholm län
  "BC", // Bacau
  "NT", // Neamţ
  "NB", // Noord-Brabant
  "NL", // Nuevo Leon
  "YT", // Yukon
  "PE", // Pescara
  "NU", // Nuoro
  "001", // Brändö
  "002", // Eckerö
  "003", // Finström
  "004", // Föglö
  "005", // Geta
  "006", // Hammarland
  "007", // Jomala
  "008", // Kumlinge
  "009", // Kökar
  "010", // Lemland
  "011", // Lumparland
  "012", // Maarianhamina
  "013", // Saltvik
  "014", // Sottunga
  "015", // Koebenhavns amt
  "016", // Vårdö
  "051", // Märket
  "AK", // Alaska
  "UO", // Ust’-Ordynsky Autonomous Okrug
  "CB", // Castelo Branco
  "SV", // Suceava
  "PM", // Permskaya Kraj
  "KP", // Komi-Permyatsky Autonomous Okrug
  "TO", // Toledo
  "HM", // Khmel'nyts'ka Oblast'
  "YN", // Yunnan
  "TN", // Tennessee
  "OM", // Omsk
  "KN", // Kurgan
  "OB", // Orenburg
  "KE", // Kildare
  "BA", // Badajoz
  "KO", // Kyivs'ka Oblast'
  "AL", // Alabama
  "GA", // Georgia
  "KK", // Kilkenny
  "TM", // Timiş
  "HK", // Khabarovsk
  "EA", // Yevreyskaya Autonomous Oblast
  "SL", // Sevastopol'
  "EV", // Evora
  "MG", // Minas Gerais
  "AM", // Amstetten
  "CK", // Chukotka Autonomous Okrug
  "PK", // Pernik
  "BU", // Burgos
  "YA", // Yambol
  "IR", // Irkutsk
  "CT", // Connecticut
  "HA", // Henan
  "KY", // Kentucky
  "TU", // Tulln
  "KT", // Kamchatka
  "IB", // Baleares
  "MI", // Michigan
  "BR", // Brăila
  "HR", // Harghita
  "VI", // Vinnyts'ka Oblast'
  "MA", // Massachusetts
  "HO", // Horn
  "GC", // Graz
  "TF", // Tenerife
  "CE", // Caserta
  "ML", // Melilla
  "COL", // Colima
  "DF", // Oietrito Federal
  "EMX", // Estado de México
  "GTO", // Guanajuato
  "HGO", // Hidalgo
  "JAL", // Jalisco
  "MIC", // Michalovce
  "MOR", // Morelos
  "NAY", // Nayarit
  "PUE", // Puebla
  "QRO", // Querétaro de Arteaga
  "TLX", // Tlaxcala
  "VER", // Veracruz-Llave
  "AGS", // Agusan del Sur
  "BCS", // Baja California Sur
  "CHH", // Chihuahua
  "COA", // Coahuila de Zaragoza
  "DGO", // Durango
  "SLP", // San Luis Potosí
  "SIN", // Sinaloa
  "SON", // Sonora
  "TMS", // Tamaulipas
  "ZAC", // Zacatecas
  "CAM", // Camiguin
  "CHS", // Chiapas
  "GRO", // Guerrero
  "OAX", // Oaxaca
  "QTR", // Quintana Roo
  "TAB", // Tabasco
  "YUC", // Yucatán
  "SP", // La Spezia
  "LO", // La Rioja
  "KL", // Klagenfurt-Land
  "AR", // Arkansas
  "NO", // Novara
  "VO", // Volyos'ka Oblast'
  "NV", // Nevada
  "PS", // Pesaro e Urbino
  "MU", // Murcia
  "MO", // Missouri
  "OR", // Oregon
  "LP", // Lipetsk
  "TV", // Treviso
  "SM", // Satu Mare
  "YR", // Yaroslavl
  "KS", // Kansas
  "TL", // Tulcea
  "VR", // Vila Real
  "TB", // Tambov
  "RA", // Ravenna
  "NN", // Nizhni Novgorod
  "IV", // Coquimbo
  "VL", // Vâlcea
  "KU", // Kufstein
  "KG", // Kaluga
  "BO", // Bologna
  "VG", // Volgograd
  "SA", // Salamanca
  "SR", // Santarem
  "UL", // Ulyanovsk
  "KI", // Kirovohrads'ka Oblast'
  "TA", // Taranto
  "MR", // Republic of Marij-El
  "MD", // Maryland
  "UD", // Udine
  "CU", // Cuenca
  "KR", // Respublika Krym
  "KC", // Klagenfurt
  "ST", // Setubal
  "KM", // Republic of Kalmykia
  "SO", // Solothurn
  "RO", // Rovigo
  "CN", // Chernivets'ka Oblast'
  "IN", // Indiana
  "AO", // Aosta
  "DA", // Delta Amacuro
  "KB", // Kitzbühel
  "AD", // Republic of Adygeya
  "FJL", // Franz Josef Land
  "C", // Uppsala län
  "B", // Barcelona
  "S", // Värmlands län
  "H", // Kalmar län
  "P", // Palencia
  "X", // Gävleborgs län
  "N", // Hallands län
  "E", // Östergötlands län
  "T", // Örebro län
  "W", // Dalarna län
  "M", // Skåne län
  "G", // Kronobergs län
  "A", // Alicante
  "J", // Jaen
  "D", // Södermanlands län
  "K", // Blekinge län
  "F", // Jönköpings län
  "Y", // Västernorrlands län
  "L", // Lleida
  "R", // Mazowieckie
  "U", // Västmanlands län
  "Z", // Jämtlands län
  "V", // Valencia
  "Q", // Kwangju
  "ES", // Espírito Santo
  "GO", // Gorizia
  "SC", // Sichuan
  "SE", // Sevilla
  "AP", // Ascoli Piceno
  "PB", // Paraíba
  "RN", // Rimini
  "PI", // Pisa
  "AC", // Västerbottens län
  "MS", // Mississippi
  "RR", // Roraima
  "RJ", // Rio de Janeiro
  "RS", // Ruse
  "PR", // Parma
  "PA", // Pennsylvania
  "MT", // Montana
  "HI", // Hainan
  "II", // Antofagasta
  "III", // Atacama
  "I", // Gotlands län
  "XV", // Arica y Parinacota
  "RM", // Roma
  "VII", // Maule
  "VIII", // Bío-Bío
  "IX", // La Araucanía
  "XIV", // Los Ríos
  "XI", // Aisén del General Carlos Ibáñez del Campo
  "XII", // Magallanes
  "KA", // Kărdžali
  "01", // Zagrebačka županija
  "02", // Krapinsko-Zagorska županija
  "ASU", // Asunción
  "03", // Sisačko-Moslavačka županija
  "09", // Ličko-Senjska županija
  "06", // Koprivničko-Križevačka županija
  "05", // Varaždinska županija
  "04", // Karlovačka županija
  "08", // Primorsko-Goranska županija
  "07", // Bjelovarsko-Bilogorska županija
  "IS", // Iaşi
  "CA", // California
  "SJ", // Sălaj
  "CO", // Colorado
  "FD", // Florida
  "FS", // Flores
  "DU", // Durazno
  "RV", // Rivera
  "LA", // Louisiana
  "TT", // Treinta y Tres
  "CL", // Călăraşi
  "LH", // Louth
  "AN", // Ancona
  "DC", // District of Columbia
  "FA", // Falcón
  "GU", // Guadalajara
  "ME", // Maine
  "NE", // Nebraska
  "PO", // Poltavs'ka Oblast'
  "SU", // Sums'ka Oblast'
  "TR", // Teleorman
  "VA", // Virginia
  "ZU", // Zulia
  "ACT", // Australian Capital Territory
  "NSW", // New South Wales
  "VIC", // Victoria
  "QLD", // Queensland
  "WA", // Washington
  "TAS", // Tasman
  "MV", // Mecklenburg-Vorpommern
  "NCD", // National Capital District
  "CPM", // Central
  "CPK", // Chimbu
  "EHG", // Eastern Highlands
  "EBR", // East New Britain
  "ESW", // East Sepik
  "EPW", // Enga
  "GPK", // Gulf
  "MPM", // Madang
  "MRL", // Manus
  "MBA", // Milne Bay
  "MPL", // Morobe
  "NIK", // New Ireland
  "NPP", // Northern
  "NSA", // Northern Samar
  "SAN", // Santaun
  "SHM", // Southern Highlands
  "WPD", // Western
  "WHM", // Western Highlands
  "WBR", // West New Britain
  "AUK", // Auckland
  "BOP", // Bay of Plenty
  "NTL", // Northland
  "WKO", // Waikato
  "GIS", // Gisborne
  "HKB", // Hawkes Bay
  "MWT", // Manawatu-Wanganui
  "TKI", // Taranaki
  "WGN", // Wellington
  "CAN", // Camarines Norte
  "MBH", // Marlborough
  "NSN", // Nelson
  "WTC", // West Coast
  "OTA", // Otago
  "STL", // Southland
  "O", // Västra Götalands län
  "WC", // Wien
  "JO", // St. Johann
  "ZE", // Zell Am See
  "BL", // Basel Landschaft
  "BN", // Bistrita-Nasaud
  "GD", // Guangdong
  "GF", // Gänserndorf
  "HL", // Heilongjiang
  "LF", // Lilienfeld
  "NK", // Neunkirchen
  "PC", // Piacenza
  "PL", // Pleven
  "SB", // Sibiu
  "SW", // Schwechat
  "WB", // Wr.Neustadt-Bezirk
  "WN", // Wr.Neustadt
  "WT", // Waidhofen/Thaya
  "WU", // Wien-Umgebung
  "WY", // Wyoming
  "ZT", // Zwettl
  "EC", // Eisenstadt
  "EU", // Eisenstadt-Umgebung
  "GS", // Gansu
  "JE", // Jennersdorf
  "ND", // North Dakota
  "OP", // Oberpullendorf
  "OW", // Obwalden
  "EF", // Eferding
  "FR", // Freiburg / Fribourg
  "GM", // Gmunden
  "GR", // Graubuenden / Grisons
  "LC", // Lecco
  "LL", // Linz-Land
  "RI", // Rhode Island
  "SD", // Shandong
  "UU", // Urfahr
  "VB", // Verbano Cusio Ossola
  "WE", // Wels
  "WL", // Wels-Land
  "BM", // Bruck-Mürzzuschlag
  "DL", // Donegal
  "FB", // Feldbach
  "FF", // Fürstenfeld
  "GB", // Gröbming
  "HB", // Hubei
  "HF", // Hartberg-Fürstenfeld
  "JU", // Jura
  "KF", // Knittelfeld
  "LB", // Limburg
  "LE", // Leon
  "LI", // Livorno
  "LN", // Liaoning
  "MZ", // Mürzzuschlag
  "WZ", // Weiz
  "IC", // Innsbruck
  "IL", // Illinois
  "IM", // Imperia
  "LZ", // Lienz
  "RE", // Reggio Emilia
  "SZ", // Schwyz
  "FE", // Ferrara
  "HE", // Hebei
  "VK", // Völkermarkt
  "WO", // Wolfsberg
  "BZ", // Buzău
  "DO", // Donets'ka Oblast'
  "FK", // Feldkirch
  "BW", // Baden-Württemberg
  "HT", // Hainaut
  "LG", // Liêge
  "NM", // Nei Mongol
  "LU", // Luhans'ka Oblast'
  "OV", // Overijssel
  "WV", // West Virginia
  "PD", // Padova
  "KD", // Kjustendil
  "SF", // Sofija
  "LV", // L'vivs'ka Oblast'
  "VT", // Vermont
  "MN", // Minnesota
  "VD", // Waadt / Vaud
  "RZ", // Razgrad
  "SS", // Guipuzcoa
  "SN", // Shaanxi
  "VN", // Vrancea
  "2A", // Corse-du-Sud
  "2B", // Haute-Corse
  "020", // Frederiksborg amt
  "025", // Roskilde amt
  "030", // Vestsjaellands amt
  "035", // Storstrøm amt
  "040", // Bornholms amt
  "042", // Fyns amt
  "050", // Sínderjylland amt
  "055", // Ribe amt
  "060", // Vejle amt
  "065", // Ringkøbing amt
  "070", // Århus amt
  "076", // Viborg amt
  "080", // Nordjyllands amt
  "CI", // Carbonia-Iglesias
  "OG", // Ogliastra
  "OT", // Olt
  "VS", // Wallis / Valais
  "BB", // Brandenburg
  "BE", // Bern
  "BY", // Freistaat Bayern
  "HH", // Freie und Hansestadt Hamburg
  "NI", // Mykolaivs'ka Oblast'
  "NW", // Nidwalden
  "RP", // Rheinland-Pfalz
  "SH", // Shanghai
  "TH", // Freistaat Thüringen
  "GY", // Gyõr
  "ZA", // Zakarpats'ka Oblast'
  "VE", // Venezia
  "BP", // Budapest
  "NG", // Nógrád
  "CS", // Castellon
  "CW", // Carlow
  "LS", // Laois
  "LM", // Leitrim
  "LK", // Limerick
  "LD", // Longford
  "MH", // Mehedinţi
  "OY", // Offaly
  "WD", // Waterford
  "WH", // Westmeath
  "WX", // Wexford
  "WW", // Wicklow
  "GE", // Genf / Genève
  "AT", // Asti
  "BI", // Vizcaya
  "VC", // Viana do Castelo
  "BG", // Bragança
  "BS", // Basel Stadt
  "CR", // Chernihivs'ka Oblast'
  "PV", // Pavia
  "PN", // Pordenone
  "TS", // Trieste
  "FO", // Forlì
  "FC", // Forlì-Cesena
  "FI", // Firenze
  "PT", // Porto
  "SI", // Siena
  "CH", // Cherkas'ka Oblast'
  "AQ", // L'Aquila
  "TE", // Ternopil's'ka Oblast'
  "FM", // Fermo
  "MC", // Macerata
  "PU", // Pesaro e Urbino
  "PZ", // Potenza
  "BT", // Boto'ani
  "FG", // Foggia
  "CZ", // Catanzaro
  "RC", // Reggio Calabria
  "VV", // Vibo Valentia
  "AV", // Avila
  "NA", // Navarra
  "LT", // Latina
  "PG", // Portalegre
  "AG", // Aargau
  "EN", // Enna
  "RG", // Ragusa
  "TP", // Trapani
  "DR", // Drenthe
  "ZH", // Zhytomyrs'ka Oblast'
  "FL", // Florida
  "NH", // New Hampshire
  "UT", // Utah
  "ZL", // Zeeland
  "BJ", // Beijing
  "LR", // Leiria
  "LX", // Lisboa
  "HD", // Hunedoara
  "IF", // Ivano-Frankivs'ka Oblast'
  "GL", // Glarus
  "BH", // Bihor
  "CJ", // Cluj
  "MM", // Maramureş
  "BV", // Braşov
  "CV", // Covasna
  "DJ", // Dolj
  "GJ", // Gorj
  "DB", // Dâmboviţa
  "PH", // Prahova
  "OU", // Ourense
  "SG", // St. Gallen
  "HU", // Huesca
  "GI", // Girona
  "CC", // Caceres
  "BD", // Norrbottens län
  "AI", // Appenzell Innerrhoden
  "TI", // Tessin / Ticino
  "TG", // Thurgau
  "UR", // Uri
  "ZG", // Zug
  "DN", // Dnipropetrovs'ka Oblast'
  "OD", // Odes'ka Oblast'
  "ZP", // Zaporiz'ka Oblast'
  "KV", // Kyïv
  "NJ", // New Jersey
  "NY", // New York
  "DE", // Delaware
  "NC", // North Carolina
  "OK", // Oklahoma
  "TX", // Texas
  "AZ", // Arizona
  "ID", // Idaho
  "OH", // Ohio
  "WI", // Wisconsin
  "IA", // Iowa
  "AH", // Anhui
  "CQ", // Chongqing
  "FJ", // Fujian
  "GX", // Guangxi Zhuangzu
  "GZ", // Guizhou
  "HN", // Hunan
  "JL", // Jilin
  "JS", // Jiangsu
  "JX", // Jiangxi
  "NX", // Ningxia Huizu
  "QH", // Qinghai
  "SX", // Shanxi
  "TJ", // Tianjin
  "XJ", // Xinjiang Uygur
  "XZ", // Xizang
  "ZJ", // Zhejiang
  "AUR", // Aurora
  "BTG", // Batangas
  "CAV", // Cavite
  "LAG", // Laguna
  "MAD", // Marinduque
  "MDC", // Mindoro Occidental
  "MDR", // Mindoro Oriental
  "PLW", // Palawan
  "QUE", // Quezon
  "RIZ", // Rizal
  "ROM", // Romblon
  "ILN", // Ilocos Norte
  "ILS", // Ilocos Sur
  "LUN", // La Union
  "PAN", // Pangasinan
  "BTN", // Batanes
  "CAG", // Cagayan
  "ISA", // Isabela
  "NUV", // Nueva Vizcaya
  "QUI", // Quirino
  "ABR", // Abra
  "APA", // Praha 1
  "BEN", // Benguet
  "IFU", // Ifugao
  "KAL", // Kalinga-Apayso
  "MOU", // Mountain Province
  "BAN", // Banovce n. Bebr.
  "BUL", // Bulacan
  "NUE", // Nueva Ecija
  "PAM", // Pampanga
  "TAR", // Tarlac
  "ZMB", // Zambales
  "ALB", // Albay
  "CAS", // Camarines Sur
  "CAT", // Catanduanes
  "MAS", // Masbate
  "SOR", // Sorsogon
  "BIL", // Biliran
  "EAS", // Eastern Samar
  "LEY", // Leyte
  "SLE", // Southern Leyte
  "WSA", // Western Samar
  "AKL", // Aklan
  "ANT", // Antique
  "CAP", // Capiz
  "GUI", // Guimaras
  "ILI", // Iloilo
  "NEC", // Negroe Occidental
  "BOH", // Bohol
  "CEB", // Cebu
  "NER", // Negros Oriental
  "SIG", // Siquijor
  "ZAN", // Zamboanga del Norte
  "ZAS", // Zamboanga del Sur
  "ZSI", // Zamboanga Sibugay
  "NCO", // North Cotabato
  "SUK", // Sultan Kudarat
  "SAR", // Sarangani
  "SCO", // South Cotabato
  "BAS", // Basilan
  "LAS", // Lanao del Sur
  "MAG", // Maguindanao
  "SLU", // Stara Lubovna
  "TAW", // Tawi-Tawi
  "LAN", // Lanao del Norte
  "BUK", // Bukidnon
  "MSC", // Misamis Occidental
  "MSR", // Misamis Oriental
  "COM", // Compostela Valley
  "DAV", // Davao del Norte
  "DAS", // Davao del Sur
  "DAO", // Davao Oriental
  "AGN", // Agusan del Norte
  "SUN", // Surigao del Norte
  "SUR", // Surigao del Sur
  "APB", // Praha 2
  "APC", // Praha 3
  "APD", // Praha 4
  "APE", // Praha 5
  "APF", // Praha 6
  "APG", // Praha 7
  "APH", // Praha 8
  "API", // Praha 9
  "APJ", // Praha 10
  "BBN", // Benesov
  "BBE", // Beroun
  "BKD", // Kladno
  "BKO", // Kolin
  "BKH", // Kutna Hora
  "BME", // Melnik
  "BMB", // Mlada Boleslav
  "BNY", // Nymburk
  "BPZ", // Praha zapad
  "BPV", // Praha vychod
  "BPB", // Pribram
  "BRA", // Rakovnik
  "CBU", // Ceske Budejovice
  "CCK", // Cesky Krumlov
  "CJH", // Jindrichuv Hradec
  "CPE", // Pelhrimov
  "CPI", // Pisek
  "CPR", // Prachatice
  "CST", // Strakonice
  "CTA", // Tabor
  "DDO", // Domazlice
  "DCH", // Cheb
  "DKV", // Karlovy Vary
  "DKL", // Klatovy
  "DPM", // Plzen mesto
  "DPJ", // Plzen jih
  "DPS", // Plzen sever
  "DRO", // Rokycany
  "DSO", // Sokolov
  "DTA", // Tachov
  "ECL", // Ceska Lipa
  "EDE", // Decin
  "ECH", // Chomutov
  "EJA", // Jablonec n. Nisou
  "ELI", // Liberec
  "ELT", // Litomerice
  "ELO", // Louny
  "EMO", // Most
  "ETE", // Teplice
  "EUL", // Usti nad Labem
  "FHB", // Havlickuv Brod
  "FHK", // Hradec Kralove
  "FCR", // Chrudim
  "FJI", // Jicin
  "FNA", // Nachod
  "FPA", // Pardubice
  "FRK", // Rychn n. Kneznou
  "FSE", // Semily
  "FSV", // Svitavy
  "FTR", // Trutnov
  "FUO", // Usti nad Orlici
  "GBL", // Blansko
  "GBM", // Brno mesto
  "GBV", // Brno venkov
  "GBR", // Breclav
  "GHO", // Hodonin
  "GJI", // Jihlava
  "GKR", // Kromeriz
  "GPR", // Prostejov
  "GTR", // Trebic
  "GUH", // Uherske Hradiste
  "GVY", // Vyskov
  "GZL", // Zlin
  "GZN", // Znojmo
  "GZS", // Zdar nad Sazavou
  "HBR", // Bruntal
  "HFM", // Frydek-Mistek
  "HJE", // Jesenik
  "HKA", // Karvina
  "HNJ", // Novy Jicin
  "HOL", // Olomouc
  "HOP", // Opava
  "HOS", // Ostrava
  "HPR", // Prerov
  "HSU", // Sumperk
  "HVS", // Vsetin
  "BAA", // Bratislava 1
  "BAB", // Bratislava 2
  "BAC", // Bratislava 3
  "BAD", // Bratislava 4
  "BAE", // Bratislava 5
  "MAL", // Malacky
  "PEZ", // Pezinok
  "SEN", // Senec
  "DST", // Dunajska Streda
  "GAL", // Galanta
  "HLO", // Hlohovec
  "PIE", // Piestany
  "SEA", // Senica
  "SKA", // Skalica
  "TRN", // Trnava
  "ILA", // Ilava
  "MYJ", // Myjava
  "NMV", // Nove Mesto n. Vah
  "PAR", // Partizanske
  "PBY", // Povazska Bystrica
  "PRI", // Prievidza
  "PUC", // Puchov
  "TNC", // Trencin
  "KOM", // Komarno
  "LVC", // Levice
  "NIT", // Nitra
  "NZA", // Nove Zamky
  "SAL", // Sala
  "TOP", // Topolcany
  "ZMO", // Zlate Moravce
  "BYT", // Bytca
  "CAD", // Cadca
  "DKU", // Dolny Kubin
  "KNM", // Kysucke N. Mesto
  "LMI", // Liptovsky Mikulas
  "MAR", // Martin
  "NAM", // Namestovo
  "RUZ", // Ruzomberok
  "TTE", // Turcianske Teplice
  "TVR", // Tvrdosin
  "ZIL", // Zilina
  "BBY", // Banska Bystrica
  "BST", // Banska Stiavnica
  "BRE", // Brezno
  "DET", // Detva
  "KRU", // Krupina
  "LUC", // Lucenec
  "POL", // Poltar
  "REV", // Revuca
  "RSO", // Rimavska Sobota
  "VKR", // Velky Krtis
  "ZAR", // Zarnovica
  "ZIH", // Ziar nad Hronom
  "ZVO", // Zvolen
  "GEL", // Gelnica
  "KEA", // Kosice 1
  "KEB", // Kosice 2
  "KEC", // Kosice 3
  "KED", // Kosice 4
  "KEO", // Kosice-okolie
  "ROZ", // Roznava
  "SOB", // Sobrance
  "SNV", // Spisska Nova Ves
  "TRE", // Trebisov
  "BAR", // Bardejov
  "HUM", // Humenne
  "KEZ", // Kezmarok
  "LEV", // Levoca
  "MED", // Medzilaborce
  "POP", // Poprad
  "PRE", // Presov
  "SAB", // Sabinov
  "SNI", // Snina
  "STR", // Stropkov
  "SVI", // Svidnik
  "VRT", // Vranov nad Toplou
] as const;

export const PrimaryAdministrativeSubdivisionEnum = enums(
  primaryAdministrativeSubdivision
);
export type PrimaryAdministrativeSubdivisionEnum = Infer<
  typeof PrimaryAdministrativeSubdivisionEnum
>;
