// generated by scripts/adif_tables.ts
import { enums, Infer } from "superstruct";

export const propagationMode = [
  "AS", // Aircraft Scatter
  "AUE", // Aurora-E
  "AUR", // Aurora
  "BS", // Back scatter
  "ECH", // EchoLink
  "EME", // Earth-Moon-Earth
  "ES", // Sporadic E
  "F2", // F2 Reflection
  "FAI", // Field Aligned Irregularities
  "GWAVE", // Ground Wave
  "INTERNET", // Internet-assisted
  "ION", // Ionoscatter
  "IRL", // IRLP
  "LOS", // Line of Sight (includes transmission through obstacles such as walls)
  "MS", // Meteor scatter
  "RPT", // Terrestrial or atmospheric repeater or transponder
  "RS", // Rain scatter
  "SAT", // Satellite
  "TEP", // Trans-equatorial
  "TR", // Tropospheric ducting
] as const;

export const PropagationModeEnum = enums(propagationMode);
export type PropagationModeEnum = Infer<typeof PropagationModeEnum>;
