// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const qslRcvd = [
  "Y", // an incoming QSL card has been received the QSO has been confirmed by the online service
  "N", // an incoming QSL card has not been received the QSO has not been confirmed by the online service
  "R", // the logging station has requested a QSL card the logging station has requested the QSO be uploaded to the online service
  "I",
  "V", // DXCC award credit granted for the QSL card - instead use <CREDIT_GRANTED:39>DXCC:card,DXCC_BAND:card,DXCC_MODE:card DXCC credit granted for the LoTW confirmation - instead use <CREDIT_GRANTED:39>DXCC:lotw,DXCC_BAND:lotw,DXCC_MODE:lotw
] as const;

export const QslRcvdEnum = coerce(enums(qslRcvd), string(), (value) => {
  const foundValue = qslRcvd.find(
    (v) => v.toUpperCase() == value.toUpperCase()
  );

  return foundValue ?? value;
});

export type QslRcvdEnum = Infer<typeof QslRcvdEnum>;
