// generated by scripts/adif_tables.ts
import { enums, Infer } from "superstruct";

export const qslSent = [
  "Y", // an outgoing QSL card has been sent the QSO has been uploaded to, and accepted by, the online service
  "N", // do not send an outgoing QSL card do not upload the QSO to the online service
  "R", // the contacted station has requested a QSL card the contacted station has requested the QSO be uploaded to the online service
  "Q", // an outgoing QSL card has been selected to be sent a QSO has been selected to be uploaded to the online service
  "I",
] as const;

export const QslSentEnum = enums(qslSent);
export type QslSentEnum = Infer<typeof QslSentEnum>;
