// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const qslVia = [
  "B", // bureau
  "D", // direct
  "E", // electronic
  "M", // manager
] as const;

export const QslViaEnum = coerce(enums(qslVia), string(), (value) => {
  const foundValue = qslVia.find((v) => v.toUpperCase() == value.toUpperCase());

  return foundValue ?? value;
});

export type QslViaEnum = Infer<typeof QslViaEnum>;
