// generated by scripts/adif_tables.ts
import { enums, Infer } from "superstruct";

export const qsoComplete = [
  "Y", // yes
  "N", // no
  "NIL", // not heard
  "?", // uncertain
] as const;

export const QsoCompleteEnum = enums(qsoComplete);
export type QsoCompleteEnum = Infer<typeof QsoCompleteEnum>;
