// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const qsoComplete = [
  "Y", // yes
  "N", // no
  "NIL", // not heard
  "?", // uncertain
] as const;

export const QsoCompleteEnum = coerce(enums(qsoComplete), string(), (value) => {
  const foundValue = qsoComplete.find(
    (v) => v.toUpperCase() == value.toUpperCase()
  );

  return foundValue ?? value;
});

export type QsoCompleteEnum = Infer<typeof QsoCompleteEnum>;
