// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const qsoDownloadStatus = [
  "Y", // the QSO has been downloaded from the online service
  "N", // the QSO has not been downloaded from the online service
  "I", // ignore or invalid
] as const;

export const QsoDownloadStatusEnum = coerce(
  enums(qsoDownloadStatus),
  string(),
  (value) => {
    const foundValue = qsoDownloadStatus.find(
      (v) => v.toUpperCase() == value.toUpperCase(),
    );

    return foundValue ?? value;
  },
);

export type QsoDownloadStatusEnum = Infer<typeof QsoDownloadStatusEnum>;
