// generated by scripts/adif_tables.ts
import { enums, Infer } from "superstruct";

export const qsoUploadStatus = [
  "Y", // the QSO has been uploaded to, and accepted by, the online service
  "N", // do not upload the QSO to the online service
  "M", // the QSO has been modified since being uploaded to the online service
] as const;

export const QsoUploadStatusEnum = enums(qsoUploadStatus);
export type QsoUploadStatusEnum = Infer<typeof QsoUploadStatusEnum>;
