// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const region = [
  "NONE", // Not within a WAE or CQ region that is within a DXCC entity
  "IV", // ITU Vienna
  "AI", // African Italy
  "SY", // Sicily
  "BI", // Bear Island
  "SI", // Shetland Islands
  "KO", // Kosovo
  "ET", // European Turkey
] as const;

export const RegionEnum = coerce(enums(region), string(), (value) => {
  const foundValue = region.find((v) => v.toUpperCase() == value.toUpperCase());

  return foundValue ?? value;
});

export type RegionEnum = Infer<typeof RegionEnum>;
