// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const secondaryAdministrativeSubdivision = [
  "AK,Aleutians East", // Aleutians East
  "AK,Aleutians Islands", // Aleutians Islands
  "AK,Aleutians West", // Aleutians West
  "AK,Anchorage", // Anchorage
  "AK,Angoon", // Angoon
  "AK,Barrow", // Barrow
  "AK,Bethel", // Bethel
  "AK,Bristol Bay", // Bristol Bay
  "AK,Cordova-McCarthy", // Cordova-McCarthy
  "AK,Denali", // Denali
  "AK,Dillingham", // Dillingham
  "AK,Fairbanks", // Fairbanks
  "AK,Fairbanks North Star", // Fairbanks North Star
  "AK,First Judicial District", // First Judicial District
  "AK,Fourth Judicial District", // Fourth Judicial District
  "AK,Haines", // Haines
  "AK,Juneau", // Juneau
  "AK,Hoonah-Angoon", // Hoonah-Angoon
  "AK,Kenai Peninsula", // Kenai Peninsula
  "AK,Kenai-Cook Inlet", // Kenai-Cook Inlet
  "AK,Ketchikan", // Ketchikan
  "AK,Ketchikan Gateway", // Ketchikan Gateway
  "AK,Kobuk", // Kobuk
  "AK,Kodiak Island", // Kodiak Island
  "AK,Kuskokwim", // Kuskokwim
  "AK,Kusilvak", // Kusilvak
  "AK,Lake and Peninsula", // Lake and Peninsula
  "AK,Lynn Canal-Icy Straits", // Lynn Canal-Icy Straits
  "AK,Matanuska-Susitna", // Matanuska-Susitna
  "AK,Nome", // Nome
  "AK,North Slope", // North Slope
  "AK,Northwest Arctic", // Northwest Arctic
  "AK,Outer Ketchikan", // Outer Ketchikan
  "AK,Palmer-Wasilla-Talkeetna", // Palmer-Wasilla-Talkeetna
  "AK,Petersburg", // Petersburg
  "AK,Pribilof Islands", // Pribilof Islands
  "AK,Prince of Wales", // Prince of Wales
  "AK,Prince of Wales-Hyder", // Prince of Wales-Hyder
  "AK,Prince of Wales-Outer Ketchikan", // Prince of Wales-Outer Ketchikan
  "AK,Saint Matthew Island", // Saint Matthew Island
  "AK,Second Judicial District", // Second Judicial District
  "AK,Seward", // Seward
  "AK,Sitka", // Sitka
  "AK,Skagway-Hoonah-Angoon", // Skagway-Hoonah-Angoon
  "AK,Skagway", // Skagway
  "AK,Skagway-Yakuta", // Skagway-Yakutat
  "AK,Skagway-Yakutat-Angoon", // Skagway-Yakutat-Angoon
  "AK,Southeast Fairbanks", // Southeast Fairbanks
  "AK,Third Judicial District", // Third Judicial District
  "AK,Upper Yukon", // Upper Yukon
  "AK,Valdez-Chitina-Whittier", // Valdez-Chitina-Whittier
  "AK,Valdez-Cordova", // Valdez-Cordova
  "AK,Wade Hampton", // Wade Hampton
  "AK,Wales-Hyder", // Wales-Hyder
  "AK,Wrangell", // Wrangell
  "AK,Wrangell-Petersburg", // Wrangell-Petersburg
  "AK,Yakutat", // Yakutat
  "AK,Yukon-Koyukuk", // Yukon-Koyukuk
] as const;

export const SecondaryAdministrativeSubdivisionEnum = coerce(
  enums(secondaryAdministrativeSubdivision),
  string(),
  (value) => {
    const foundValue = secondaryAdministrativeSubdivision.find(
      (v) => v.toUpperCase() == value.toUpperCase()
    );

    return foundValue ?? value;
  }
);

export type SecondaryAdministrativeSubdivisionEnum = Infer<
  typeof SecondaryAdministrativeSubdivisionEnum
>;
