// generated by scripts/adif_tables.ts
import { enums, Infer, coerce, string } from "superstruct";

export const secondaryAdministrativeSubdivisionAlt = [
  "NZ_Regions:Northland/Far North", // Far North
  "NZ_Regions:Northland/Whangarei", // Whangarei
  "NZ_Regions:Northland/Kaipara", // Kaipara
  "NZ_Regions:Auckland/Rodney", // Rodney
  "NZ_Regions:Auckland/North Shore", // North Shore
  "NZ_Regions:Auckland/Waitakere", // Waitakere
  "NZ_Regions:Auckland/Auckland", // Auckland
  "NZ_Regions:Auckland/Manukau", // Manukau
  "NZ_Regions:Auckland/Papakura", // Papakura
  "NZ_Regions:Auckland/Franklin", // Franklin
  "NZ_Regions:Waikato/Thames-Coromandel", // Thames-Coromandel
  "NZ_Regions:Waikato/Hauraki", // Hauraki
  "NZ_Regions:Waikato/Waikato", // Waikato
  "NZ_Regions:Waikato/Matamata Piako", // Matamata Piako
  "NZ_Regions:Waikato/Hamilton", // Hamilton
  "NZ_Regions:Waikato/Waipa", // Waipa
  "NZ_Regions:Waikato/Otorohanga", // Otorohanga
  "NZ_Regions:Waikato/South Waikato", // South Waikato
  "NZ_Regions:Waikato/Waitomo", // Waitomo
  "NZ_Regions:Waikato/Taupo", // Taupo
  "NZ_Regions:Bay of Plenty/Western Bay of Plenty", // Western Bay of Plenty
  "NZ_Regions:Bay of Plenty/Tauranga", // Tauranga
  "NZ_Regions:Bay of Plenty/Rotorua", // Rotorua
  "NZ_Regions:Bay of Plenty/Kawerau", // Kawerau
  "NZ_Regions:Bay of Plenty/Whakatane", // Whakatane
  "NZ_Regions:Bay of Plenty/Opotiki", // Opotiki
  "NZ_Regions:Gisborne/Gisborne", // Gisborne
  "NZ_Regions:Hawkes Bay/Wairoa", // Wairoa
  "NZ_Regions:Hawkes Bay/Hastings", // Hastings
  "NZ_Regions:Hawkes Bay/Napier", // Napier
  "NZ_Regions:Hawkes Bay/Central Hawkes Bay", // Central Hawkes Bay
  "NZ_Regions:Taranaki/New Plymouth", // New Plymouth
  "NZ_Regions:Taranaki/Stratford", // Stratford
  "NZ_Regions:Taranaki/South Taranaki", // South Taranaki
  "NZ_Regions:Wanganui-Manawatu/Ruapehu", // Ruapehu
  "NZ_Regions:Wanganui-Manawatu/Wanganui", // Wanganui
  "NZ_Regions:Wanganui-Manawatu/Rangitikei", // Rangitikei
  "NZ_Regions:Wanganui-Manawatu/Manawatu", // Manawatu
  "NZ_Regions:Wanganui-Manawatu/Palmerston North", // Palmerston North
  "NZ_Regions:Wanganui-Manawatu/Horowhenua", // Horowhenua
  "NZ_Regions:Wanganui-Manawatu/Tararua", // Tararua
  "NZ_Regions:Wellington/Masterton", // Masterton
  "NZ_Regions:Wellington/Carterton", // Carterton
  "NZ_Regions:Wellington/South Wairarapa", // South Wairarapa
  "NZ_Regions:Wellington/Kapiti Coast", // Kapiti Coast
  "NZ_Regions:Wellington/Porirua", // Porirua
  "NZ_Regions:Wellington/Upper Hutt", // Upper Hutt
  "NZ_Regions:Wellington/Lower Hutt", // Lower Hutt
  "NZ_Regions:Wellington/Wellington", // Wellington
  "NZ_Regions:Nelson/Nelson", // Nelson
  "NZ_Regions:Marlborough/Marlborough", // Marlborough
  "NZ_Regions:Tasman/Tasman", // Tasman
  "NZ_Regions:West Coast/Buller", // Buller
  "NZ_Regions:West Coast/Grey", // Grey
  "NZ_Regions:West Coast/Westland", // Westland
  "NZ_Regions:Canterbury/Kaikoura", // Kaikoura
  "NZ_Regions:Canterbury/Hurunui", // Hurunui
  "NZ_Regions:Canterbury/Selwyn", // Selwyn
  "NZ_Regions:Canterbury/Waimakariri", // Waimakariri
  "NZ_Regions:Canterbury/Christchurch", // Christchurch
  "NZ_Regions:Canterbury/Banks Peninsula", // Banks Peninsula
  "NZ_Regions:Canterbury/Ashburton", // Ashburton
  "NZ_Regions:Canterbury/Mackenzie", // Mackenzie
  "NZ_Regions:Canterbury/Timaru", // Timaru
  "NZ_Regions:Canterbury/Waimate", // Waimate
  "NZ_Regions:Otago/Waitaki", // Waitaki
  "NZ_Regions:Otago/Queenstown-Lakes", // Queenstown-Lakes
  "NZ_Regions:Otago/Central Otago", // Central Otago
  "NZ_Regions:Otago/Dunedin", // Dunedin
  "NZ_Regions:Otago/Clutha", // Clutha
  "NZ_Regions:Southland/Gore", // Gore
  "NZ_Regions:Southland/Southland", // Southland
  "NZ_Regions:Southland/Invercargill", // Invercargill
] as const;

export const SecondaryAdministrativeSubdivisionAltEnum = coerce(
  enums(secondaryAdministrativeSubdivisionAlt),
  string(),
  (value) => {
    const foundValue = secondaryAdministrativeSubdivisionAlt.find(
      (v) => v.toUpperCase() == value.toUpperCase(),
    );

    return foundValue ?? value;
  },
);

export type SecondaryAdministrativeSubdivisionAltEnum = Infer<
  typeof SecondaryAdministrativeSubdivisionAltEnum
>;
