export * from "./adif.js";
export * from "./parse.js";
export * from "./exportPaperlog.js";
export * from "./filter.js";
export * from "./adif/adifRecord.js";
export * from "./exportAdif.js";
export * from "./importAdif.js";
import pkg from "../package.json" with { type: "json" };
const version = pkg.version;
export { version };
